name: semantic-pull-request

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: read
  statuses: write

jobs:
  check-sem-pr:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            perf
            refactor
            revert
            docs
            style
            test
            build
            ci
            chore

